In [1]:
import keras
from tensorflow.contrib import rnn
import quandl
import pandas as pd

C:\Users\Boon Yang\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.

In [2]:
quandl.ApiConfig.api_key = "CwbpyqG6PfiQmiEB8vGe"

In [46]:
data=quandl.get_table("SHARADAR/SF1", ticker="SNAP")
data

,ticker,dimension,calendardate,datekey,reportperiod,lastupdated,accoci,assets,assetsavg,assetsc,...,sharesbas,shareswa,shareswadil,sps,tangibles,taxassets,taxexp,taxliabilities,tbvps,workingcapital
None,,,,,,,,,,,,,,,,,,,,,
0,SNAP,MRY,2017-12-31,2017-12-31,2017-12-31,2018-08-08,14157000.0,3.421566e+09,3.720299e+09,2.366794e+09,...,1.204261e+09,1.204261e+09,None,0.685,2.615211e+09,0.0,-18342000.0,0.0,2.172,2.020538e+09
1,SNAP,MRY,2016-12-31,2016-12-31,2016-12-31,2018-08-08,-2057000.0,1.722792e+09,1.330864e+09,1.179985e+09,...,NaN,NaN,None,NaN,1.327673e+09,0.0,-7080000.0,0.0,NaN,1.023241e+09
2,SNAP,MRY,2015-12-31,2015-12-31,2015-12-31,2018-08-08,0.0,9.389360e+08,NaN,6.925640e+08,...,NaN,NaN,None,NaN,7.617620e+08,0.0,-7589000.0,0.0,NaN,5.363060e+08
3,SNAP,MRT,2018-06-30,2018-06-30,2018-06-30,2018-08-08,8207000.0,2.950713e+09,3.274172e+09,1.868850e+09,...,1.258171e+09,1.258171e+09,None,0.784,2.168034e+09,0.0,-12885000.0,0.0,1.723,1.589508e+09
4,SNAP,MRT,2018-03-31,2018-03-31,2018-03-31,2018-08-08,20963000.0,3.182030e+09,3.505362e+09,2.111231e+09,...,1.227036e+09,1.227036e+09,None,0.738,2.379798e+09,0.0,-13750000.0,0.0,1.939,1.809874e+09
5,SNAP,MRT,2017-12-31,2017-12-31,2017-12-31,2018-08-08,14157000.0,3.421566e+09,3.720299e+09,2.366794e+09,...,1.204261e+09,1.204261e+09,None,0.685,2.615211e+09,0.0,-18342000.0,0.0,2.172,2.020538e+09
6,SNAP,MRT,2017-09-30,2017-09-30,2017-09-30,2018-08-08,11682000.0,3.542380e+09,3.295606e+09,2.547731e+09,...,1.197155e+09,1.197155e+09,None,0.589,2.764945e+09,0.0,-15399000.0,0.0,2.310,2.251567e+09
7,SNAP,MRT,2017-06-30,2017-06-30,2017-06-30,2018-08-08,3590000.0,3.875474e+09,NaN,3.046898e+09,...,1.179126e+09,1.179126e+09,None,0.530,3.236644e+09,0.0,-9970000.0,0.0,2.745,2.788589e+09
8,SNAP,MRT,2017-03-31,2017-03-31,2017-03-31,2018-08-08,-1635000.0,4.041777e+09,NaN,3.463206e+09,...,1.157270e+09,1.157270e+09,None,0.445,3.629791e+09,0.0,-10215000.0,0.0,3.137,3.220921e+09
9,SNAP,MRT,2016-12-31,2016-12-31,2016-12-31,2018-08-08,-2057000.0,1.722792e+09,1.330864e+09,1.179985e+09,...,NaN,NaN,None,NaN,1.327673e+09,0.0,-7080000.0,0.0,NaN,1.023241e+09
10,SNAP,MRT,2016-09-30,2016-09-30,2016-09-30,2018-08-08,NaN,NaN,NaN,NaN,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,SNAP,MRT,2016-06-30,2016-06-30,2016-06-30,2018-08-08,NaN,NaN,NaN,NaN,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,SNAP,MRT,2016-03-31,2016-03-31,2016-03-31,2018-08-08,NaN,NaN,NaN,NaN,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,SNAP,MRT,2015-12-31,2015-12-31,2015-12-31,2018-08-08,0.0,9.389360e+08,NaN,6.925640e+08,...,NaN,NaN,None,NaN,7.617620e+08,0.0,-7589000.0,0.0,NaN,5.363060e+08
14,SNAP,MRQ,2018-06-30,2018-06-30,2018-06-30,2018-08-08,8207000.0,2.950713e+09,NaN,1.868850e+09,...,1.258171e+09,1.258171e+09,None,0.208,2.168034e+09,0.0,1077000.0,0.0,1.723,1.589508e+09
15,SNAP,MRQ,2018-03-31,2018-03-31,2018-03-31,2018-08-08,20963000.0,3.182030e+09,NaN,2.111231e+09,...,1.227036e+09,1.227036e+09,None,0.188,2.379798e+09,0.0,1578000.0,0.0,1.939,1.809874e+09
16,SNAP,MRQ,2017-12-31,2017-12-31,2017-12-31,2018-08-08,14157000.0,3.421566e+09,NaN,2.366794e+09,...,1.204261e+09,1.204261e+09,None,0.237,2.615211e+09,0.0,-3240000.0,0.0,2.172,2.020538e+09
17,SNAP,MRQ,2017-09-30,2017-09-30,2017-09-30,2018-08-08,11682000.0,3.542380e+09,NaN,2.547731e+09,...,1.197155e+09,1.197155e+09,None,0.174,2.764945e+09,0.0,-12300000.0,0.0,2.310,2.251567e+09
18,SNAP,MRQ,2017-06-30,2017-06-30,2017-06-30,2018-08-08,3590000.0,3.875474e+09,NaN,3.046898e+09,...,1.179126e+09,1.179126e+09,None,0.154,3.236644e+09,0.0,212000.0,0.0,2.745,2.788589e+09
19,SNAP,MRQ,2017-03-31,2017-03-31,2017-03-31,2018-08-08,-1635000.0,4.041777e+09,NaN,3.463206e+09,...,1.157270e+09,1.157270e+09,None,0.129,3.629791e+09,0.0,-3014000.0,0.0,3.137,3.220921e+09
20,SNAP,MRQ,2016-12-31,2016-12-31,2016-12-31,2018-08-08,-2057000.0,1.722792e+09,NaN,1.179985e+09,...,NaN,NaN,None,NaN,1.327673e+09,0.0,-297000.0,0.0,NaN,1.023241e+09
21,SNAP,MRQ,2016-09-30,2016-09-30,2016-09-30,2018-08-08,NaN,NaN,NaN,NaN,...,NaN,NaN,None,NaN,NaN,NaN,-6871000.0,NaN,NaN,NaN
22,SNAP,MRQ,2016-06-30,2016-06-30,2016-06-30,2018-08-08,NaN,NaN,NaN,NaN,...,NaN,NaN,None,NaN,NaN,NaN,-33000.0,NaN,NaN,NaN
23,SNAP,MRQ,2016-03-31,2016-03-31,2016-03-31,2018-08-08,NaN,NaN,NaN,NaN,...,NaN,NaN,None,NaN,NaN,NaN,121000.0,NaN,NaN,NaN
24,SNAP,MRQ,2015-12-31,2015-12-31,2015-12-31,2018-08-08,0.0,9.389360e+08,NaN,6.925640e+08,...,NaN,NaN,None,NaN,7.617620e+08,0.0,NaN,0.0,NaN,5.363060e+08
25,SNAP,ARY,2017-12-31,2018-02-22,2017-12-31,2018-08-08,14157000.0,3.421566e+09,3.720299e+09,2.366794e+09,...,1.227036e+09,1.227036e+09,None,0.672,2.615211e+09,0.0,-18342000.0,0.0,2.131,2.020538e+09
26,SNAP,ARY,2016-12-31,2017-02-27,2016-12-31,2018-08-08,-2057000.0,1.722792e+09,NaN,1.179985e+09,...,1.157270e+09,1.157270e+09,None,0.350,1.327673e+09,0.0,-7080000.0,0.0,1.147,1.023241e+09
27,SNAP,ART,2018-06-30,2018-08-08,2018-06-30,2018-08-08,8207000.0,2.950713e+09,3.274172e+09,1.868850e+09,...,1.277353e+09,1.277353e+09,None,0.772,2.168034e+09,0.0,-12885000.0,0.0,1.697,1.589508e+09
28,SNAP,ART,2018-03-31,2018-05-02,2018-03-31,2018-08-08,20963000.0,3.182030e+09,3.505362e+09,2.111231e+09,...,1.258171e+09,1.258171e+09,None,0.720,2.379798e+09,0.0,-13750000.0,0.0,1.891,1.809874e+09
29,SNAP,ART,2017-12-31,2018-02-22,2017-12-31,2018-08-08,14157000.0,3.421566e+09,3.720299e+09,2.366794e+09,...,1.227036e+09,1.227036e+09,None,0.672,2.615211e+09,0.0,-18342000.0,0.0,2.131,2.020538e+09
30,SNAP,ART,2017-09-30,2017-11-08,2017-09-30,2018-08-08,11682000.0,3.542380e+09,3.295606e+09,2.547731e+09,...,1.204261e+09,1.204261e+09,None,NaN,2.764945e+09,0.0,NaN,0.0,2.296,2.251567e+09
31,SNAP,ART,2017-06-30,2017-08-11,2017-06-30,2018-08-08,3590000.0,3.875474e+09,NaN,3.046898e+09,...,1.197155e+09,1.197155e+09,None,NaN,3.236644e+09,0.0,NaN,0.0,2.704,2.788589e+09
32,SNAP,ART,2017-03-31,2017-05-11,2017-03-31,2018-08-08,-1635000.0,4.041777e+09,NaN,3.463206e+09,...,1.179126e+09,1.179126e+09,None,NaN,3.629791e+09,0.0,NaN,0.0,3.078,3.220921e+09
33,SNAP,ART,2016-12-31,2017-02-27,2016-12-31,2018-08-08,-2057000.0,1.722792e+09,NaN,1.179985e+09,...,1.157270e+09,1.157270e+09,None,0.350,1.327673e+09,0.0,-7080000.0,0.0,1.147,1.023241e+09
34,SNAP,ARQ,2018-06-30,2018-08-08,2018-06-30,2018-08-08,8207000.0,2.950713e+09,NaN,1.868850e+09,...,1.277353e+09,1.277353e+09,None,0.205,2.168034e+09,0.0,1077000.0,0.0,1.697,1.589508e+09
35,SNAP,ARQ,2018-03-31,2018-05-02,2018-03-31,2018-08-08,20963000.0,3.182030e+09,NaN,2.111231e+09,...,1.258171e+09,1.258171e+09,None,0.183,2.379798e+09,0.0,1578000.0,0.0,1.891,1.809874e+09
36,SNAP,ARQ,2017-12-31,2018-02-22,2017-12-31,2018-08-08,14157000.0,3.421566e+09,NaN,2.366794e+09,...,1.227036e+09,1.227036e+09,None,0.233,2.615211e+09,0.0,-3240000.0,0.0,2.131,2.020538e+09
37,SNAP,ARQ,2017-09-30,2017-11-08,2017-09-30,2018-08-08,11682000.0,3.542380e+09,NaN,2.547731e+09,...,1.204261e+09,1.204261e+09,None,0.173,2.764945e+09,0.0,-12300000.0,0.0,2.296,2.251567e+09
38,SNAP,ARQ,2017-06-30,2017-08-11,2017-06-30,2018-08-08,3590000.0,3.875474e+09,NaN,3.046898e+09,...,1.197155e+09,1.197155e+09,None,0.152,3.236644e+09,0.0,212000.0,0.0,2.704,2.788589e+09
39,SNAP,ARQ,2017-03-31,2017-05-11,2017-03-31,2018-08-08,-1635000.0,4.041777e+09,NaN,3.463206e+09,...,1.179126e+09,1.179126e+09,None,0.127,3.629791e+09,0.0,-3014000.0,0.0,3.078,3.220921e+09
40,SNAP,ARQ,2016-12-31,2017-02-27,2016-12-31,2018-08-08,-2057000.0,1.722792e+09,NaN,1.179985e+09,...,1.157270e+09,1.157270e+09,None,NaN,1.327673e+09,0.0,NaN,0.0,1.147,1.023241e+09

# Features

In [4]:
for i in data.columns:
    print(i)

ticker
dimension
calendardate
datekey
reportperiod
lastupdated
accoci
assets
assetsavg
assetsc
assetsnc
assetturnover
bvps
capex
cashneq
cashnequsd
cor
consolinc
currentratio
de
debt
debtc
debtnc
debtusd
deferredrev
depamor
deposits
divyield
dps
ebit
ebitda
ebitdamargin
ebitdausd
ebitusd
ebt
eps
epsdil
epsusd
equity
equityavg
equityusd
ev
evebit
evebitda
fcf
fcfps
fxusd
gp
grossmargin
intangibles
intexp
invcap
invcapavg
inventory
investments
investmentsc
investmentsnc
liabilities
liabilitiesc
liabilitiesnc
marketcap
ncf
ncfbus
ncfcommon
ncfdebt
ncfdiv
ncff
ncfi
ncfinv
ncfo
ncfx
netinc
netinccmn
netinccmnusd
netincdis
netincnci
netmargin
opex
opinc
payables
payoutratio
pb
pe
pe1
ppnenet
prefdivis
price
ps
ps1
receivables
retearn
revenue
revenueusd
rnd
roa
roe
roic
ros
sbcomp
sgna
sharefactor
sharesbas
shareswa
shareswadil
sps
tangibles
taxassets
taxexp
taxliabilities
tbvps
workingcapital

# Target

In [5]:
data["price"]

None
0      154.120
1      112.710
2      114.710
3      100.750
4       68.964
5       95.301
6       57.757
7       41.760
8       26.053
9       18.320
10      21.924
11      10.997
12       7.600
13       2.664
14       1.478
15       1.051
16       1.108
17       1.839
18       2.319
19       1.384
20       0.761
21       0.799
22       1.335
23     185.110
24     167.780
25     169.230
26     154.120
27     144.020
28     143.660
29     115.820
        ...
357      5.538
358      4.477
359      2.242
360      1.899
361      1.641
362      1.407
363      1.407
364      1.334
365      1.025
366      1.014
367      1.071
368      1.829
369      1.784
370      1.500
371      1.364
372      1.664
373      1.406
374      1.031
375      3.629
376      3.672
377      3.580
378      3.569
379      1.933
380      1.598
381      1.348
382      1.422
383      1.355
384      1.105
385      0.685
386      0.565
Name: price, Length: 387, dtype: float64

# Missing Values

In [6]:
# Function to calculate missing values by column# Funct 
def missing_values_table(df):
    '''Returns a table that has the number and percentage of missing values, and prints out some additional information. '''
    # Total missing values
    mis_val = df.isnull().sum()

    # Percentage of missing values
    mis_val_percent = 100 * df.isnull().sum() / len(df)

    # Make a table with the results
    mis_val_table = pd.concat([mis_val, mis_val_percent], axis=1)

    # Rename the columns
    mis_val_table_ren_columns = mis_val_table.rename(
    columns = {0 : 'Missing Values', 1 : '% of Total Values'})

    # Sort the table by percentage of missing descending
    mis_val_table_ren_columns = mis_val_table_ren_columns[
        mis_val_table_ren_columns.iloc[:,1] != 0].sort_values(
    '% of Total Values', ascending=False).round(1)

    # Print some summary information
    print ("Your selected dataframe has " + str(df.shape[1]) + " columns.\n"      
        "There are " + str(mis_val_table_ren_columns.shape[0]) +
          " columns that have missing values.")

    # Return the dataframe with missing information
    return mis_val_table_ren_columns

In [7]:
#Check
missing_values_table(data)

Your selected dataframe has 111 columns.
There are 100 columns that have missing values.

                Missing Values  % of Total Values
roe                        185               47.8
assetturnover              185               47.8
roa                        185               47.8
roic                       185               47.8
invcapavg                  184               47.5
assetsavg                  184               47.5
equityavg                  184               47.5
ros                        177               45.7
evebitda                    20                5.2
evebit                      20                5.2
pe                          17                4.4
ps                          17                4.4
ev                          14                3.6
ps1                         12                3.1
pe1                         12                3.1
marketcap                   11                2.8
pb                          11                2.8
sharesbas                   11                2.8
ncfx                         8                2.1
ncfdiv                       8                2.1
opinc                        8                2.1
opex                         8                2.1
netincnci                    8                2.1
netmargin                    8                2.1
netincdis                    8                2.1
netinccmnusd                 8                2.1
netinccmn                    8                2.1
ncff                         8                2.1
ncfi                         8                2.1
ncfinv                       8                2.1
...                        ...                ...
cashneq                      8                2.1
capex                        8                2.1
bvps                         8                2.1
assetsnc                     8                2.1
assetsc                      8                2.1
ebitdamargin                 8                2.1
ebitdausd                    8                2.1
ebitusd                      8                2.1
ebt                          8                2.1
assets                       8                2.1
liabilitiesc                 8                2.1
liabilities                  8                2.1
investmentsnc                8                2.1
investmentsc                 8                2.1
investments                  8                2.1
inventory                    8                2.1
invcap                       8                2.1
intexp                       8                2.1
intangibles                  8                2.1
grossmargin                  8                2.1
gp                           8                2.1
fcfps                        8                2.1
fcf                          8                2.1
equityusd                    8                2.1
equity                       8                2.1
epsusd                       8                2.1
epsdil                       8                2.1
eps                          8                2.1
workingcapital               8                2.1
sharefactor                  2                0.5

[100 rows x 2 columns]

# Fill missing data with mean

In [8]:
for feature in data.select_dtypes(include = 'float64').columns:
    data[feature].fillna(data[feature].mean(), inplace = True)

In [9]:
missing_values_table(data)

Your selected dataframe has 111 columns.
There are 0 columns that have missing values.

Empty DataFrame
Columns: [Missing Values, % of Total Values]
Index: []

# Entries that contain ARQ, ARY and ART

In [10]:
mask=data["dimension"].isin(['ARQ', 'ARY', 'ART']) # a seres of booleans
data[mask]

,ticker,dimension,calendardate,datekey,reportperiod,lastupdated,accoci,assets,assetsavg,assetsc,...,sharesbas,shareswa,shareswadil,sps,tangibles,taxassets,taxexp,taxliabilities,tbvps,workingcapital
None,,,,,,,,,,,,,,,,,,,,,
200,AAPL,ARY,2017-12-31,2017-11-03,2017-09-30,2018-08-01,-1.500000e+08,3.753190e+11,3.465412e+11,1.286450e+11,...,5.134312e+09,5217242000,5.251692e+09,43.938000,3.673040e+11,0.000000e+00,1.573800e+10,0.0,71.329,2.783100e+10
201,AAPL,ARY,2016-12-31,2016-10-26,2016-09-24,2018-08-01,6.340000e+08,3.216860e+11,3.064622e+11,1.068690e+11,...,5.332313e+09,5470820000,5.500281e+09,39.416000,3.130660e+11,0.000000e+00,1.568500e+10,0.0,58.333,2.786300e+10
202,AAPL,ARY,2015-12-31,2015-10-28,2015-09-26,2018-08-01,-3.450000e+08,2.904790e+11,2.716795e+11,8.937800e+10,...,5.575331e+09,5753421000,5.793069e+09,40.622000,2.814700e+11,5.546000e+09,1.912100e+10,0.0,49.845,8.768000e+09
203,AAPL,ARY,2014-12-31,2014-10-27,2014-09-27,2018-08-01,1.082000e+09,2.318390e+11,2.213830e+11,6.853100e+10,...,5.864840e+09,6085572000,6.122663e+09,30.037000,2.230810e+11,4.318000e+09,1.397300e+10,0.0,37.595,5.083000e+09
204,AAPL,ARY,2013-12-31,2013-10-30,2013-09-28,2018-08-01,-4.710000e+08,2.070000e+11,1.994218e+11,7.328600e+10,...,6.298166e+09,6477317000,6.521634e+09,26.386000,2.012440e+11,3.453000e+09,1.311800e+10,0.0,31.797,2.962800e+10
205,AAPL,ARY,2012-12-31,2012-10-31,2012-09-29,2018-08-01,4.990000e+08,1.760640e+11,1.571438e+11,5.765300e+10,...,6.584844e+09,6543726000,6.617485e+09,23.917000,1.707050e+11,2.583000e+09,1.403000e+10,0.0,25.991,1.911100e+10
206,AAPL,ARY,2011-12-31,2011-10-26,2011-09-24,2018-08-01,4.430000e+08,1.163710e+11,1.011938e+11,4.498800e+10,...,6.505863e+09,6469806000,6.556515e+09,16.731000,1.119390e+11,2.014000e+09,8.283000e+09,0.0,17.227,1.701800e+10
207,AAPL,ARY,2010-12-31,2010-10-27,2010-09-25,2018-08-01,-4.600000e+07,7.518300e+10,6.272275e+10,4.167800e+10,...,6.421150e+09,6366227000,6.472984e+09,10.245000,7.410000e+10,1.636000e+09,4.527000e+09,0.0,11.575,2.095600e+10
208,AAPL,ARY,2009-12-31,2009-10-27,2009-09-26,2018-08-01,8.400000e+07,5.385100e+10,4.700375e+10,3.626500e+10,...,6.304749e+09,6251112000,6.349035e+09,5.845000,5.339800e+10,2.101000e+09,2.280000e+09,0.0,8.494,1.698300e+10
209,AAPL,ARY,2008-12-31,2008-11-05,2008-09-27,2018-08-01,8.000000e+06,3.957200e+10,3.294775e+10,3.469000e+10,...,6.222546e+09,6171144000,6.314973e+09,5.263000,3.908000e+10,1.447000e+09,2.061000e+09,0.0,6.293,2.059800e+10
210,AAPL,ARY,2007-12-31,2007-11-15,2007-09-29,2018-08-01,6.300000e+07,2.534700e+10,2.129150e+10,2.195600e+10,...,6.128782e+09,6052165000,6.225044e+09,3.967000,2.501000e+10,7.820000e+08,1.512000e+09,0.0,4.103,1.265700e+10
211,AAPL,ARY,2006-12-31,2006-12-29,2006-09-30,2018-08-01,2.200000e+07,1.720500e+10,1.437800e+10,1.450900e+10,...,6.014916e+09,5908406000,6.142682e+09,3.269000,1.702800e+10,6.070000e+08,8.290000e+08,0.0,2.849,8.038000e+09
212,AAPL,ARY,2005-12-31,2005-12-01,2005-09-24,2018-08-01,0.000000e+00,1.155100e+10,1.037800e+10,1.030000e+10,...,5.899376e+09,5659073000,5.997460e+09,2.462000,1.145500e+10,3.310000e+08,4.800000e+08,0.0,1.992,6.816000e+09
213,AAPL,ARY,2004-12-31,2004-12-03,2004-09-25,2018-08-01,-1.500000e+07,8.050000e+09,7.244750e+09,7.055000e+09,...,5.628810e+09,5202260000,5.422354e+09,1.591000,7.953000e+09,2.310000e+08,1.070000e+08,294000000.0,1.481,4.375000e+09
214,AAPL,ARY,2003-12-31,2003-12-19,2003-09-27,2018-08-01,-3.500000e+07,6.815000e+09,6.471500e+09,5.887000e+09,...,5.148289e+09,5048834000,5.088524e+09,1.229000,6.706000e+09,1.900000e+08,2.400000e+07,235000000.0,1.323,3.530000e+09
215,AAPL,ARY,2002-12-31,2002-12-19,2002-09-28,2018-08-01,-4.900000e+07,6.298000e+09,6.244250e+09,5.388000e+09,...,5.027898e+09,4970308000,5.064990e+09,1.155000,6.179000e+09,1.660000e+08,2.200000e+07,229000000.0,1.230,3.730000e+09
216,AAPL,ARY,2001-12-31,2001-12-21,2001-09-29,2018-08-01,-2.200000e+07,6.021000e+09,6.052000e+09,5.143000e+09,...,4.924115e+09,4838582000,4.838582e+09,1.108000,6.021000e+09,1.690000e+08,-1.500000e+07,266000000.0,1.226,3.625000e+09
217,AAPL,ARY,2000-12-31,2000-12-14,2000-09-30,2018-08-01,2.440000e+08,6.803000e+09,7.082000e+09,5.427000e+09,...,4.702348e+09,4543952000,5.044536e+09,1.757000,6.803000e+09,1.620000e+08,3.060000e+08,463000000.0,1.486,3.494000e+09
218,AAPL,ARY,1999-12-31,1999-12-22,1999-09-25,2018-08-01,1.060000e+08,5.161000e+09,4.926750e+09,4.285000e+09,...,4.512452e+09,4008396000,4.876592e+09,1.530000,5.161000e+09,1.430000e+08,7.500000e+07,208000000.0,1.175,2.736000e+09
219,AAPL,ARY,1998-12-31,1998-12-23,1998-09-25,2018-08-01,0.000000e+00,4.289000e+09,4.104750e+09,3.698000e+09,...,3.788954e+09,3695272000,4.701676e+09,1.608000,4.289000e+09,1.820000e+08,2.000000e+07,173000000.0,1.135,2.178000e+09
220,AAPL,ARY,1997-12-31,1997-12-05,1997-09-26,2018-08-01,0.000000e+00,4.233000e+09,9.597745e+10,3.424000e+09,...,3.583816e+09,3529736000,3.529736e+09,2.006000,4.233000e+09,2.590000e+08,0.000000e+00,264000000.0,1.199,1.606000e+09
221,AAPL,ART,2018-06-30,2018-08-01,2018-06-30,2018-08-01,-3.111000e+09,3.491970e+11,3.747030e+11,1.157610e+11,...,4.829926e+09,4882167000,4.926609e+09,52.287000,3.491970e+11,0.000000e+00,1.427900e+10,0.0,71.525,2.721300e+10
222,AAPL,ART,2018-03-31,2018-05-02,2018-03-31,2018-08-01,-3.064000e+09,3.675020e+11,3.736970e+11,1.300530e+11,...,4.915138e+09,5024877000,5.068493e+09,49.238000,3.675020e+11,0.000000e+00,1.510500e+10,0.0,73.137,4.073300e+10
223,AAPL,ART,2017-12-31,2018-02-02,2017-12-30,2018-08-01,-8.410000e+08,4.067940e+11,3.654545e+11,1.438100e+11,...,5.074013e+09,5112877000,5.157787e+09,46.779000,3.987560e+11,0.000000e+00,1.641400e+10,0.0,77.991,2.802200e+10
224,AAPL,ART,2017-09-30,2017-11-03,2017-09-30,2018-08-01,-1.500000e+08,3.753190e+11,3.465412e+11,1.286450e+11,...,5.134312e+09,5217242000,5.251692e+09,43.938000,3.673040e+11,0.000000e+00,1.573800e+10,0.0,71.329,2.783100e+10
225,AAPL,ART,2017-06-30,2017-08-02,2017-07-01,2018-08-01,-5.450000e+08,3.451730e+11,3.331330e+11,1.128750e+11,...,5.165228e+09,5195088000,5.233499e+09,43.023000,3.370680e+11,0.000000e+00,1.570900e+10,0.0,64.882,3.157300e+10
226,AAPL,ART,2017-03-31,2017-05-03,2017-04-01,2018-08-01,-4.220000e+08,3.345320e+11,3.232402e+11,1.019900e+11,...,5.213840e+09,5225791000,5.261688e+09,42.186000,3.264420e+11,0.000000e+00,1.579100e+10,0.0,62.467,2.864800e+10
227,AAPL,ART,2016-12-31,2017-02-01,2016-12-31,2018-08-01,2.450000e+08,3.311410e+11,3.159265e+11,1.033320e+11,...,5.246540e+09,5298661000,5.327995e+09,41.165000,3.228700e+11,0.000000e+00,1.576200e+10,0.0,60.934,1.920200e+10
228,AAPL,ART,2016-09-30,2016-10-26,2016-09-24,2018-08-01,6.340000e+08,3.216860e+11,3.064622e+11,1.068690e+11,...,5.332313e+09,5470820000,5.500281e+09,39.416000,3.130660e+11,0.000000e+00,1.568500e+10,0.0,58.333,2.786300e+10
229,AAPL,ART,2016-06-30,2016-07-27,2016-06-25,2018-08-01,-1.070000e+08,3.056020e+11,2.986605e+11,9.376100e+10,...,5.388443e+09,5443058000,5.472781e+09,40.471000,2.968350e+11,0.000000e+00,1.644900e+10,0.0,54.535,2.227500e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,AAPL,ARQ,2004-12-31,2005-02-01,2004-12-25,2018-08-01,-3.000000e+06,9.362000e+09,9.597745e+10,8.322000e+09,...,5.720204e+09,5523224000,5.867218e+09,0.632000,9.266000e+09,2.810000e+08,1.340000e+08,0.0,1.678,5.098000e+09
358,AAPL,ARQ,2004-09-30,2004-12-03,2004-09-25,2018-08-01,-1.500000e+07,8.050000e+09,9.597745e+10,7.055000e+09,...,5.628810e+09,5369588000,5.676538e+09,0.438000,7.953000e+09,2.310000e+08,4.100000e+07,294000000.0,1.481,4.375000e+09
359,AAPL,ARQ,2004-06-30,2004-08-05,2004-06-26,2018-08-01,-1.800000e+07,7.223000e+09,9.597745e+10,6.286000e+09,...,5.430951e+09,5250322000,5.496694e+09,0.384000,7.124000e+09,2.270000e+08,2.400000e+07,256000000.0,1.357,4.131000e+09
360,AAPL,ARQ,2004-03-31,2004-05-06,2004-03-27,2018-08-01,-1.000000e+07,6.735000e+09,9.597745e+10,5.784000e+09,...,5.320592e+09,5114858000,5.295220e+09,0.373000,6.629000e+09,2.160000e+08,1.800000e+07,265000000.0,1.296,3.804000e+09
361,AAPL,ARQ,2003-12-31,2004-02-10,2003-12-27,2018-08-01,-3.100000e+07,6.971000e+09,9.597745e+10,6.029000e+09,...,5.176223e+09,5074300000,5.212312e+09,0.395000,6.864000e+09,2.180000e+08,2.400000e+07,259000000.0,1.353,3.647000e+09
362,AAPL,ARQ,2003-09-30,2003-12-19,2003-09-27,2018-08-01,-3.500000e+07,6.815000e+09,9.597745e+10,5.887000e+09,...,5.148289e+09,5070590000,5.132414e+09,0.338000,6.706000e+09,1.900000e+08,1.400000e+07,235000000.0,1.323,3.530000e+09
363,AAPL,ARQ,2003-06-30,2003-08-12,2003-06-28,2018-08-01,-1.900000e+07,6.441000e+09,9.597745e+10,5.546000e+09,...,5.075013e+09,5051102000,5.092878e+09,0.306000,6.329000e+09,1.760000e+08,7.000000e+06,218000000.0,1.253,3.521000e+09
364,AAPL,ARQ,2003-03-31,2003-05-13,2003-03-29,2018-08-01,-3.600000e+07,6.361000e+09,9.597745e+10,5.468000e+09,...,5.118560e+09,5046860000,5.071402e+09,0.292000,6.247000e+09,1.680000e+08,5.000000e+06,215000000.0,1.238,3.461000e+09
365,AAPL,ARQ,2002-12-31,2003-02-10,2002-12-28,2018-08-01,-4.000000e+07,6.269000e+09,9.597745e+10,5.384000e+09,...,5.046700e+09,5026798000,5.026798e+09,0.293000,6.153000e+09,1.770000e+08,-2.000000e+06,238000000.0,1.224,3.789000e+09
366,AAPL,ARQ,2002-09-30,2002-12-19,2002-09-28,2018-08-01,-4.900000e+07,6.298000e+09,9.597745e+10,5.388000e+09,...,5.027898e+09,5021632000,4.995564e+09,0.287000,6.179000e+09,1.660000e+08,-1.500000e+07,229000000.0,1.230,3.730000e+09
367,AAPL,ARQ,2002-06-30,2002-08-09,2002-06-29,2018-08-01,-1.040000e+08,6.293000e+09,9.597745e+10,5.443000e+09,...,5.024403e+09,4989180000,5.136348e+09,0.286000,6.194000e+09,1.640000e+08,7.000000e+06,193000000.0,1.241,3.725000e+09
368,AAPL,ARQ,2002-03-31,2002-05-14,2002-03-30,2018-08-01,-6.200000e+07,6.264000e+09,9.597745e+10,5.414000e+09,...,4.979803e+09,4948720000,5.123566e+09,0.302000,6.183000e+09,1.610000e+08,1.500000e+07,230000000.0,1.249,3.705000e+09
369,AAPL,ARQ,2001-12-31,2002-02-11,2001-12-29,2018-08-01,-2.800000e+07,6.122000e+09,9.597745e+10,5.272000e+09,...,4.947361e+09,4918620000,5.005126e+09,0.280000,6.047000e+09,1.710000e+08,1.500000e+07,262000000.0,1.229,3.693000e+09
370,AAPL,ARQ,2001-09-30,2001-12-21,2001-09-29,2018-08-01,-2.200000e+07,6.021000e+09,9.597745e+10,5.143000e+09,...,4.924115e+09,4911494000,4.911494e+09,0.295000,6.021000e+09,1.690000e+08,2.800000e+07,266000000.0,1.226,3.625000e+09
371,AAPL,ARQ,2001-06-30,2001-08-13,2001-06-30,2018-08-01,3.000000e+06,6.071000e+09,9.597745e+10,5.248000e+09,...,4.911373e+09,4882710000,5.024768e+09,0.302000,6.071000e+09,1.730000e+08,2.600000e+07,282000000.0,1.243,3.634000e+09
372,AAPL,ARQ,2001-03-31,2001-05-14,2001-03-31,2018-08-01,6.000000e+06,6.130000e+09,9.597745e+10,5.345000e+09,...,4.886324e+09,4845120000,4.939368e+09,0.295000,6.130000e+09,1.830000e+08,1.900000e+07,280000000.0,1.265,3.550000e+09
373,AAPL,ARQ,2000-12-31,2001-02-12,2000-12-30,2018-08-01,4.100000e+07,5.986000e+09,9.597745e+10,4.926000e+09,...,4.844406e+09,4720380000,4.720380e+09,0.213000,5.986000e+09,2.310000e+08,-8.800000e+07,326000000.0,1.268,3.289000e+09
374,AAPL,ARQ,2000-09-30,2000-12-14,2000-09-30,2018-08-01,2.440000e+08,6.803000e+09,9.597745e+10,5.427000e+09,...,4.702348e+09,4577468000,5.061168e+09,0.409000,6.803000e+09,1.620000e+08,5.900000e+07,463000000.0,1.486,3.494000e+09
375,AAPL,ARQ,2000-06-30,2000-07-31,2000-07-01,2018-08-01,5.350000e+08,6.932000e+09,9.597745e+10,5.157000e+09,...,4.549567e+09,4550560000,5.065438e+09,0.401000,6.932000e+09,1.620000e+08,7.000000e+07,583000000.0,1.523,3.284000e+09
376,AAPL,ARQ,2000-03-31,2000-05-11,2000-04-01,2018-08-01,7.310000e+08,7.007000e+09,9.597745e+10,4.912000e+09,...,4.556824e+09,4540816000,5.095804e+09,0.428000,7.007000e+09,1.310000e+08,8.600000e+07,639000000.0,1.543,3.059000e+09
377,AAPL,ARQ,1999-12-31,2000-02-01,2000-01-01,2018-08-01,1.237000e+09,7.586000e+09,9.597745e+10,4.909000e+09,...,4.526512e+09,4509092000,4.995676e+09,0.520000,7.586000e+09,1.310000e+08,9.100000e+07,907000000.0,1.682,2.944000e+09
378,AAPL,ARQ,1999-09-30,1999-12-22,1999-09-25,2018-08-01,1.060000e+08,5.161000e+09,9.597745e+10,4.285000e+09,...,4.512452e+09,4393620000,4.946648e+09,0.304000,5.161000e+09,1.430000e+08,1.400000e+07,208000000.0,1.175,2.736000e+09
379,AAPL,ARQ,1999-06-30,1999-08-06,1999-06-26,2018-08-01,9.200000e+07,5.019000e+09,9.597745e+10,4.298000e+09,...,4.504648e+09,4033512000,4.890200e+09,0.386000,5.019000e+09,1.370000e+08,2.600000e+07,210000000.0,1.244,2.759000e+09
380,AAPL,ARQ,1999-03-31,1999-05-11,1999-03-27,2018-08-01,1.680000e+08,4.935000e+09,9.597745e+10,4.092000e+09,...,3.837649e+09,3818388000,4.849712e+09,0.401000,4.935000e+09,1.540000e+08,1.800000e+07,261000000.0,1.292,2.548000e+09
381,AAPL,ARQ,1998-12-31,1999-02-08,1998-12-26,2018-08-01,8.600000e+07,4.592000e+09,9.597745e+10,3.867000e+09,...,3.819679e+09,3787560000,4.817736e+09,0.451000,4.592000e+09,1.660000e+08,1.700000e+07,231000000.0,1.212,2.383000e+09
382,AAPL,ARQ,1998-09-30,1998-12-23,1998-09-25,2018-08-01,0.000000e+00,4.289000e+09,9.597745e+10,3.698000e+09,...,3.788954e+09,3779524000,4.701676e+09,0.412000,4.289000e+09,1.820000e+08,8.000000e+06,173000000.0,1.135,2.178000e+09
383,AAPL,ARQ,1998-06-30,1998-08-10,1998-06-26,2018-08-01,0.000000e+00,4.041000e+09,9.597745e+10,3.375000e+09,...,3.769903e+09,3725904000,4.810008e+09,0.376000,4.041000e+09,1.920000e+08,8.000000e+06,213000000.0,1.085,1.986000e+09
384,AAPL,ARQ,1998-03-31,1998-05-11,1998-03-27,2018-08-01,0.000000e+00,3.963000e+09,9.597745e+10,3.213000e+09,...,3.725136e+09,3695132000,4.085620e+09,0.380000,3.963000e+09,2.010000e+08,4.000000e+06,238000000.0,1.072,1.829000e+09
385,AAPL,ARQ,1997-12-31,1998-02-09,1997-12-26,2018-08-01,0.000000e+00,4.126000e+09,9.597745e+10,3.373000e+09,...,3.717506e+09,3583692000,3.915492e+09,0.440000,4.126000e+09,2.330000e+08,0.000000e+00,261000000.0,1.151,1.704000e+09
386,AAPL,ARQ,1997-09-30,1997-12-05,1997-09-26,2018-08-01,0.000000e+00,4.233000e+09,9.597745e+10,3.424000e+09,...,3.583816e+09,3529736000,5.649901e+09,9.094734,4.233000e+09,2.590000e+08,3.787586e+09,264000000.0,1.199,1.606000e+09

In [11]:
number_of_each_dimension = []
for i in data.dimension.unique():
    number_of_each_dimension.append((data['dimension'] == i).sum())

In [12]:
pd.DataFrame([data.dimension.unique(), number_of_each_dimension])

     0    1    2    3    4    5
0  MRY  MRT  MRQ  ARY  ART  ARQ
1   23   89   88   21   83   83

# MRQ data without ticker, calendardate, reportperiod and lastupdated

In [13]:
MRQ_data = data[data['dimension'] == 'MRQ'].drop(['ticker', 'calendardate', 'reportperiod', 'lastupdated'], axis = 1)
MRQ_data.head()

,dimension,datekey,accoci,assets,assetsavg,assetsc,assetsnc,assetturnover,bvps,capex,...,sharesbas,shareswa,shareswadil,sps,tangibles,taxassets,taxexp,taxliabilities,tbvps,workingcapital
None,,,,,,,,,,,,,,,,,,,,,
112,MRQ,2018-06-30,-3.111000e+09,3.491970e+11,9.597745e+10,1.157610e+11,2.334360e+11,1.022455,23.545,-3.267000e+09,...,4.915138e+09,4882167000,4.926609e+09,10.910,3.491970e+11,0.0,1.765000e+09,0.0,71.525,2.721300e+10
113,MRQ,2018-03-31,-3.064000e+09,3.675020e+11,9.597745e+10,1.300530e+11,2.374490e+11,1.022455,25.250,-4.041000e+09,...,5.074013e+09,5024877000,5.068493e+09,12.167,3.675020e+11,0.0,2.346000e+09,0.0,73.137,4.073300e+10
114,MRQ,2017-12-30,-8.410000e+08,4.067940e+11,9.597745e+10,1.438100e+11,2.629840e+11,1.022455,27.421,-2.964000e+09,...,5.134312e+09,5112877000,5.157787e+09,17.269,3.987560e+11,0.0,6.965000e+09,0.0,77.991,2.802200e+10
115,MRQ,2017-09-30,-1.500000e+08,3.753190e+11,9.597745e+10,1.286450e+11,2.466740e+11,1.022455,26.031,-4.000000e+09,...,5.165228e+09,5149427000,5.183586e+09,10.211,3.753190e+11,0.0,3.203000e+09,0.0,72.886,2.783100e+10
116,MRQ,2017-07-01,-5.450000e+08,3.451730e+11,9.597745e+10,1.128750e+11,2.322980e+11,1.022455,25.490,-2.277000e+09,...,5.213840e+09,5195088000,5.233499e+09,8.741,3.370680e+11,0.0,2.591000e+09,0.0,64.882,3.157300e+10

# X and y

In [14]:
y = MRQ_data.price

In [15]:
X = MRQ_data.datekey

In [45]:
data[['eps', 'dps', 'liabilities', 'roe']]

            eps    dps   liabilities       roe
None
0      9.270000  2.400  2.412720e+11  0.363000
1      8.350000  2.180  1.934370e+11  0.356000
2      9.280000  1.980  1.709900e+11  0.429000
3      6.490000  1.811  1.202920e+11  0.328000
4      5.720000  1.629  8.345100e+10  0.291000
5      6.380000  0.379  5.785400e+10  0.395000
6      4.007000  0.000  3.975600e+10  0.396000
7      2.201000  0.000  2.739200e+10  0.338000
8      1.317000  0.000  1.586100e+10  0.314000
9      0.991000  0.000  1.387400e+10  0.319000
10     0.577000  0.000  1.081500e+10  0.272000
11     0.337000  0.000  7.221000e+09  0.219000
12     0.234000  0.000  4.088000e+09  0.201000
13     0.051000  0.000  2.974000e+09  0.057000
14     0.014000  0.000  2.592000e+09  0.017000
15     0.013000  0.000  2.203000e+09  0.016000
16    -0.005000  0.000  2.101000e+09 -0.007000
17     0.173000  0.000  2.696000e+09  0.186000
18     0.150000  0.000  2.057000e+09  0.236000
19     0.084000  0.000  2.647000e+09  0.215000
20    -0.296000  0.000  3.033000e+09 -0.641000
21    -0.235000  0.004  3.306000e+09  0.240391
22     0.123000  0.017  5.074820e+10  0.240391
23    11.120000  2.620  2.342480e+11  0.435000
24    10.440000  2.520  2.406240e+11  0.400000
25     9.800000  2.460  2.665950e+11  0.374000
26     9.270000  2.400  2.412720e+11  0.363000
27     8.860000  2.340  2.127480e+11  0.354000
28     8.610000  2.280  2.004500e+11  0.351000
29     8.410000  2.230  1.987510e+11  0.349000
...         ...    ...           ...       ...
357    0.054000  0.000  3.572000e+09  0.240391
358    0.020000  0.000  2.974000e+09  0.240391
359    0.011000  0.000  2.411000e+09  0.240391
360    0.009000  0.000  2.245000e+09  0.240391
361    0.012000  0.000  2.641000e+09  0.240391
362    0.009000  0.000  2.592000e+09  0.240391
363    0.004000  0.000  2.243000e+09  0.240391
364    0.003000  0.000  2.222000e+09  0.240391
365   -0.001000  0.000  2.153000e+09  0.240391
366   -0.009000  0.000  2.203000e+09  0.240391
367    0.006000  0.000  2.227000e+09  0.240391
368    0.008000  0.000  2.250000e+09  0.240391
369    0.008000  0.000  2.156000e+09  0.240391
370    0.014000  0.000  2.101000e+09  0.240391
371    0.012000  0.000  2.213000e+09  0.240391
372    0.009000  0.000  2.392000e+09  0.240391
373   -0.041000  0.000  2.274000e+09  0.240391
374    0.037000  0.000  2.696000e+09  0.240391
375    0.044000  0.000  2.756000e+09  0.240391
376    0.051000  0.000  2.792000e+09  0.240391
377    0.041000  0.000  3.172000e+09  0.240391
378    0.024000  0.000  2.057000e+09  0.240391
379    0.050000  0.000  2.049000e+09  0.240391
380    0.035000  0.000  2.760000e+09  0.240391
381    0.040000  0.000  2.669000e+09  0.240391
382    0.028000  0.000  2.647000e+09  0.240391
383    0.027000  0.000  2.555000e+09  0.240391
384    0.015000  0.000  2.575000e+09  0.240391
385    0.013000  0.000  2.882000e+09  0.240391
386    1.894617  0.000  3.033000e+09  0.240391

[387 rows x 4 columns]

In [20]:
def predict_prices(dates, prices):
    
    svr_lin = svm.SVR(kernel = 'linear', C=1e3)
    svr_poly = SVR(kernel = 'poly', C=1e3, degree = 2)
    svr_rbf = SVR(kernel = 'rbf', C=1e3, gamma = 0.1)
    
    svr_lin.fit(dates, prices)
    svr_poly.fit(dates, prices)
    svr_rbf.fit(dates, prices)
    
    plt.scatter(list(dates), list(prices))
    plt.plot(dates, svr_rbf.predict(dates), color = 'red', label = 'rbf model')
    plt.plot(dates, svr_linear.predict(dates), color = 'green', label = 'rbf model')
    plt.plot(dates, svr_poly.predict(dates), color = 'blue', label = 'rbf model')
    plt.legend()
    plt.show()
    
    return svr_rbg.predict(x)[0], svr_linear.predict(x)[0], svr_poly.predict(x)[0]